baseURL = "https://saveroo.netlify.com/"
#baseURL = "http://192.168.12.1:1313"
title   = "Hello Friend..."

DefaultContentLanguage = "en"

theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

# googleAnalytics = ""
# disqusShortname = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = true
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = true
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Saveroo"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 +0700"

  # Metadata mostly used in document's head
  description = "Muhammad Surga Savero"
  keywords = "vue, react, native, frontend, backend, developer, engineer"
  images = [""]

  homeSubtitle = "Muhammad Surga Savero"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = ""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = [
  "/css/styles.css",
  "https://fonts.googleapis.com/icon?family=Material+Icons",
  "https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900|Material+Icons",
  "https://use.fontawesome.com/releases/v5.0.13/css/all.css",
  "https://cdn.jsdelivr.net/npm/animate.css@^3.5.2/animate.min.css",
#  "https://cdn.jsdelivr.net/npm/quasar@1.9.11/dist/quasar.min.css"
  ]
  customJS  = [
#  "https://cdn.jsdelivr.net/npm/vue@^2.0.0/dist/vue.min.js",
#  "https://cdn.jsdelivr.net/npm/quasar@1.9.11/dist/quasar.umd.min.js",
#  "https://cdn.jsdelivr.net/npm/quasar@1.9.11/dist/icon-set/fontawesome-v5.umd.min.js"
  ]

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"

  # Colors for favicons
  [params.favicon.color]
    mask = "#252627"
    msapplication = "#252627"
    theme = "#252627"

  [params.logo]
    logoText     = "$ cd ~/home"
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    # logoCursorColor    = "#67a2c9"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "1s"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/surgasavero"

#  [[params.social]]
#    name = "email"
#    url  = "mailto:saveroo27@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/saveroo"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/"

#  [[params.social]]
#    name = "instagram"
#    url  = "https://www.linkedin.com/"


[languages]
  [languages.en]
    subtitle  = "Hello Friend NG Theme"
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "self"
    name       = "./self"
    url        = "about/"
  [[menu.main]]
    identifier = "scratch"
    name       = "./scratch"
    url        = "posts/"
  [[menu.main]]
    identifier = "dev"
    name       = "./dev"
    url        = "dev/"
