[build]
    publish = "public"
    command = "hugo --gc --minify"
[context.production.environment]
    HUGO_VERSION = "0.67.1"
[context.deploy-preview.environment]
    HUGO_VERSION = "0.67.1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=31536000, no Etag, no Last-Modified settings"
    Content-Security-Policy = "default-src 'self' *.github.com"
    Server = "(Darwin), (Red Hat), (Ruby)"
