[build]
    publish = "public"
    command = "hugo --gc --minify"
[context.production.environment]
    HUGO_VERSION = "0.67.1"
[context.deploy-preview.environment]
    HUGO_VERSION = "0.67.1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"
    Server = "(Darwin), (Red Hat), (Ruby)"
